services:
  app:
    build: .
    container_name: api-escolar
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"  # expõe a porta 8080 na máquina e conecta na 8000 do container
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-escolar
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escolar
    ports:
      - "5432:5432"  # expõe a porta 5432 na máquina e conecta na 5432 do container
    volumes:  
      - postgres_data:/var/lib/postgresql/data  # persistência de dados do banco de dados
volumes:
  postgres_data:  # volume nomeado para persistência de dados do banco de dados
networks:
  default:
    driver: bridge  # usa o driver de rede bridge padrão do Docker